-- MySQL Script generated by MySQL Workbench
-- Wed Oct  9 16:15:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Czytelnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Czytelnik` (
  `idCzytelnik` INT NOT NULL,
  `Imie` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `Adres` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCzytelnik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wypozyczona ksiazka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wypozyczona ksiazka` (
  `idWypozyczona ksiazka` INT NOT NULL,
  `ISBN` VARCHAR(45) NOT NULL,
  `Tytul` VARCHAR(45) NOT NULL,
  `Wydawnictwo` VARCHAR(45) NOT NULL,
  `Data wypozyczenia` DATE NOT NULL,
  `Czytelnik_idCzytelnik` INT NOT NULL,
  PRIMARY KEY (`idWypozyczona ksiazka`, `Czytelnik_idCzytelnik`),
  INDEX `fk_Wypozyczona ksiazka_Czytelnik1_idx` (`Czytelnik_idCzytelnik` ASC) VISIBLE,
  CONSTRAINT `fk_Wypozyczona ksiazka_Czytelnik1`
    FOREIGN KEY (`Czytelnik_idCzytelnik`)
    REFERENCES `mydb`.`Czytelnik` (`idCzytelnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idAutor` INT NOT NULL,
  `Imie` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ksiazka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ksiazka` (
  `ksiazka_ISBN` INT NOT NULL,
  `autor_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ksiazka_ISBN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ksiazka_has_Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ksiazka_has_Autor` (
  `Ksiazka_ksiazka_ISBN` INT NOT NULL,
  `Autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`Ksiazka_ksiazka_ISBN`, `Autor_idAutor`),
  INDEX `fk_Ksiazka_has_Autor_Autor1_idx` (`Autor_idAutor` ASC) VISIBLE,
  INDEX `fk_Ksiazka_has_Autor_Ksiazka1_idx` (`Ksiazka_ksiazka_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_Ksiazka_has_Autor_Ksiazka1`
    FOREIGN KEY (`Ksiazka_ksiazka_ISBN`)
    REFERENCES `mydb`.`Ksiazka` (`ksiazka_ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ksiazka_has_Autor_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `mydb`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Czytelnik_has_Ksiazka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Czytelnik_has_Ksiazka` (
  `Czytelnik_idCzytelnik` INT NOT NULL,
  `Ksiazka_ksiazka_ISBN` INT NOT NULL,
  `Wypozyczona ksiazka` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Czytelnik_idCzytelnik`, `Ksiazka_ksiazka_ISBN`),
  INDEX `fk_Czytelnik_has_Ksiazka_Ksiazka1_idx` (`Ksiazka_ksiazka_ISBN` ASC) VISIBLE,
  INDEX `fk_Czytelnik_has_Ksiazka_Czytelnik1_idx` (`Czytelnik_idCzytelnik` ASC) VISIBLE,
  CONSTRAINT `fk_Czytelnik_has_Ksiazka_Czytelnik1`
    FOREIGN KEY (`Czytelnik_idCzytelnik`)
    REFERENCES `mydb`.`Czytelnik` (`idCzytelnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Czytelnik_has_Ksiazka_Ksiazka1`
    FOREIGN KEY (`Ksiazka_ksiazka_ISBN`)
    REFERENCES `mydb`.`Ksiazka` (`ksiazka_ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
