-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 16:08:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Druzyna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Druzyna` (
  `idDruzyna` INT NOT NULL,
  `Nazwa druzyny` VARCHAR(45) NULL,
  PRIMARY KEY (`idDruzyna`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pilkarz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pilkarz` (
  `idPilkarz` INT NOT NULL,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `Nr_koszulki` VARCHAR(45) NULL,
  `Wiek` VARCHAR(45) NULL,
  `Wzrost` VARCHAR(45) NULL,
  `Druzyna_idDruzyna` INT NOT NULL,
  PRIMARY KEY (`idPilkarz`, `Druzyna_idDruzyna`),
  INDEX `fk_Pilkarz_Druzyna_idx` (`Druzyna_idDruzyna` ASC) VISIBLE,
  CONSTRAINT `fk_Pilkarz_Druzyna`
    FOREIGN KEY (`Druzyna_idDruzyna`)
    REFERENCES `mydb`.`Druzyna` (`idDruzyna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecze` (
  `idMecze` INT NOT NULL,
  `Nr_meczu` VARCHAR(45) NULL,
  `Wynik meczu` VARCHAR(45) NULL,
  PRIMARY KEY (`idMecze`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sedzia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sedzia` (
  `idSedzia` INT NOT NULL,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `Typ_sedzii` VARCHAR(45) NULL,
  `Mecze_idMecze` INT NOT NULL,
  PRIMARY KEY (`idSedzia`, `Mecze_idMecze`),
  INDEX `fk_Sedzia_Mecze1_idx` (`Mecze_idMecze` ASC) VISIBLE,
  CONSTRAINT `fk_Sedzia_Mecze1`
    FOREIGN KEY (`Mecze_idMecze`)
    REFERENCES `mydb`.`Mecze` (`idMecze`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bramka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bramka` (
  `idBramka` INT NOT NULL,
  `Liczba bramek` VARCHAR(45) NULL,
  `Pilkarz_idPilkarz` INT NOT NULL,
  `Pilkarz_Druzyna_idDruzyna` INT NOT NULL,
  `Mecze_idMecze` INT NOT NULL,
  PRIMARY KEY (`idBramka`, `Pilkarz_idPilkarz`, `Pilkarz_Druzyna_idDruzyna`, `Mecze_idMecze`),
  INDEX `fk_Bramka_Pilkarz1_idx` (`Pilkarz_idPilkarz` ASC, `Pilkarz_Druzyna_idDruzyna` ASC) VISIBLE,
  INDEX `fk_Bramka_Mecze1_idx` (`Mecze_idMecze` ASC) VISIBLE,
  CONSTRAINT `fk_Bramka_Pilkarz1`
    FOREIGN KEY (`Pilkarz_idPilkarz` , `Pilkarz_Druzyna_idDruzyna`)
    REFERENCES `mydb`.`Pilkarz` (`idPilkarz` , `Druzyna_idDruzyna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bramka_Mecze1`
    FOREIGN KEY (`Mecze_idMecze`)
    REFERENCES `mydb`.`Mecze` (`idMecze`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sztab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sztab` (
  `idSztab` INT NOT NULL,
  `Stanowisko` VARCHAR(45) NULL,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `Druzyna_idDruzyna` INT NOT NULL,
  PRIMARY KEY (`idSztab`, `Druzyna_idDruzyna`),
  INDEX `fk_Sztab_Druzyna1_idx` (`Druzyna_idDruzyna` ASC) VISIBLE,
  CONSTRAINT `fk_Sztab_Druzyna1`
    FOREIGN KEY (`Druzyna_idDruzyna`)
    REFERENCES `mydb`.`Druzyna` (`idDruzyna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wygrana_druzyna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wygrana_druzyna` (
  `idWygrana_druzyny` INT NOT NULL,
  `Liczba wygranych meczy` VARCHAR(45) NULL,
  PRIMARY KEY (`idWygrana_druzyny`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Druzyna_has_Wygrana_druzyny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Druzyna_has_Wygrana_druzyny` (
  `Druzyna_idDruzyna` INT NOT NULL,
  `Wygrana_druzyny_idWygrana_druzyny` INT NOT NULL,
  PRIMARY KEY (`Druzyna_idDruzyna`, `Wygrana_druzyny_idWygrana_druzyny`),
  INDEX `fk_Druzyna_has_Wygrana_druzyny_Wygrana_druzyny1_idx` (`Wygrana_druzyny_idWygrana_druzyny` ASC) VISIBLE,
  INDEX `fk_Druzyna_has_Wygrana_druzyny_Druzyna1_idx` (`Druzyna_idDruzyna` ASC) VISIBLE,
  CONSTRAINT `fk_Druzyna_has_Wygrana_druzyny_Druzyna1`
    FOREIGN KEY (`Druzyna_idDruzyna`)
    REFERENCES `mydb`.`Druzyna` (`idDruzyna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Druzyna_has_Wygrana_druzyny_Wygrana_druzyny1`
    FOREIGN KEY (`Wygrana_druzyny_idWygrana_druzyny`)
    REFERENCES `mydb`.`Wygrana_druzyna` (`idWygrana_druzyny`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Druzyna_has_Mecze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Druzyna_has_Mecze` (
  `Druzyna_idDruzyna` INT NOT NULL,
  `Mecze_idMecze` INT NOT NULL,
  `Rezultat` VARCHAR(45) NULL,
  `Liczba bramek` VARCHAR(45) NULL,
  PRIMARY KEY (`Druzyna_idDruzyna`, `Mecze_idMecze`),
  INDEX `fk_Druzyna_has_Mecze_Mecze1_idx` (`Mecze_idMecze` ASC) VISIBLE,
  INDEX `fk_Druzyna_has_Mecze_Druzyna1_idx` (`Druzyna_idDruzyna` ASC) VISIBLE,
  CONSTRAINT `fk_Druzyna_has_Mecze_Druzyna1`
    FOREIGN KEY (`Druzyna_idDruzyna`)
    REFERENCES `mydb`.`Druzyna` (`idDruzyna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Druzyna_has_Mecze_Mecze1`
    FOREIGN KEY (`Mecze_idMecze`)
    REFERENCES `mydb`.`Mecze` (`idMecze`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
