-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 15:29:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Firma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Firma` (
  `idFirma` INT NOT NULL,
  `Nazwa` VARCHAR(45) NULL,
  `Adres` VARCHAR(45) NULL,
  `Telefon` VARCHAR(45) NULL,
  `Pracownicy` VARCHAR(45) NULL,
  PRIMARY KEY (`idFirma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kontahent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kontahent` (
  `idkontahent` INT NOT NULL,
  `Nazwa` VARCHAR(45) NULL,
  `typ` VARCHAR(45) NULL,
  `adres` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Firma_idFirma` INT NOT NULL,
  PRIMARY KEY (`idkontahent`, `Firma_idFirma`),
  INDEX `fk_kontahent_Firma_idx` (`Firma_idFirma` ASC) VISIBLE,
  CONSTRAINT `fk_kontahent_Firma`
    FOREIGN KEY (`Firma_idFirma`)
    REFERENCES `mydb`.`Firma` (`idFirma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dział`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dział` (
  `idDział` INT NOT NULL,
  `Nazwa` VARCHAR(45) NULL,
  PRIMARY KEY (`idDział`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pracownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pracownik` (
  `idpracownik` INT NOT NULL,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `Dział` VARCHAR(45) NULL,
  `Firma_idFirma` INT NOT NULL,
  `Dział_idDział` INT NOT NULL,
  PRIMARY KEY (`idpracownik`, `Firma_idFirma`, `Dział_idDział`),
  INDEX `fk_pracownik_Dział1_idx` (`Dział_idDział` ASC) VISIBLE,
  CONSTRAINT `fk_pracownik_Dział1`
    FOREIGN KEY (`Dział_idDział`)
    REFERENCES `mydb`.`Dział` (`idDział`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event` (
  `idevent` INT NOT NULL,
  `data` DATE NULL,
  `miejsce` VARCHAR(45) NULL,
  `kontrahent` VARCHAR(45) NULL,
  `Planowany` VARCHAR(45) NULL,
  `kontahent_idkontahent` INT NOT NULL,
  `kontahent_Firma_idFirma` INT NOT NULL,
  PRIMARY KEY (`idevent`, `kontahent_idkontahent`, `kontahent_Firma_idFirma`),
  INDEX `fk_event_kontahent1_idx` (`kontahent_idkontahent` ASC, `kontahent_Firma_idFirma` ASC) VISIBLE,
  CONSTRAINT `fk_event_kontahent1`
    FOREIGN KEY (`kontahent_idkontahent` , `kontahent_Firma_idFirma`)
    REFERENCES `mydb`.`kontahent` (`idkontahent` , `Firma_idFirma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rozliczenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rozliczenia` (
  `idrozliczenia` INT NOT NULL,
  `eventid` VARCHAR(45) NULL,
  `typ` VARCHAR(45) NULL,
  `kwota` VARCHAR(45) NULL,
  `event_idevent` INT NOT NULL,
  `event_kontahent_idkontahent` INT NOT NULL,
  `event_kontahent_Firma_idFirma` INT NOT NULL,
  PRIMARY KEY (`idrozliczenia`, `event_idevent`, `event_kontahent_idkontahent`, `event_kontahent_Firma_idFirma`),
  INDEX `fk_rozliczenia_event1_idx` (`event_idevent` ASC, `event_kontahent_idkontahent` ASC, `event_kontahent_Firma_idFirma` ASC) VISIBLE,
  CONSTRAINT `fk_rozliczenia_event1`
    FOREIGN KEY (`event_idevent` , `event_kontahent_idkontahent` , `event_kontahent_Firma_idFirma`)
    REFERENCES `mydb`.`event` (`idevent` , `kontahent_idkontahent` , `kontahent_Firma_idFirma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Koszt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Koszt` (
  `idKoszt` INT NOT NULL,
  `eventid` VARCHAR(45) NULL,
  `kwota` VARCHAR(45) NULL,
  `event_idevent` INT NOT NULL,
  `event_kontahent_idkontahent` INT NOT NULL,
  `event_kontahent_Firma_idFirma` INT NOT NULL,
  PRIMARY KEY (`idKoszt`, `event_idevent`, `event_kontahent_idkontahent`, `event_kontahent_Firma_idFirma`),
  INDEX `fk_Koszt_event1_idx` (`event_idevent` ASC, `event_kontahent_idkontahent` ASC, `event_kontahent_Firma_idFirma` ASC) VISIBLE,
  CONSTRAINT `fk_Koszt_event1`
    FOREIGN KEY (`event_idevent` , `event_kontahent_idkontahent` , `event_kontahent_Firma_idFirma`)
    REFERENCES `mydb`.`event` (`idevent` , `kontahent_idkontahent` , `kontahent_Firma_idFirma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event_has_pracownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event_has_pracownik` (
  `event_idevent` INT NOT NULL,
  `event_kontahent_idkontahent` INT NOT NULL,
  `event_kontahent_Firma_idFirma` INT NOT NULL,
  `pracownik_idpracownik` INT NOT NULL,
  `pracownik_Firma_idFirma` INT NOT NULL,
  `pracownik_Dział_idDział` INT NOT NULL,
  PRIMARY KEY (`event_idevent`, `event_kontahent_idkontahent`, `event_kontahent_Firma_idFirma`, `pracownik_idpracownik`, `pracownik_Firma_idFirma`, `pracownik_Dział_idDział`),
  INDEX `fk_event_has_pracownik_pracownik1_idx` (`pracownik_idpracownik` ASC, `pracownik_Firma_idFirma` ASC, `pracownik_Dział_idDział` ASC) VISIBLE,
  INDEX `fk_event_has_pracownik_event1_idx` (`event_idevent` ASC, `event_kontahent_idkontahent` ASC, `event_kontahent_Firma_idFirma` ASC) VISIBLE,
  CONSTRAINT `fk_event_has_pracownik_event1`
    FOREIGN KEY (`event_idevent` , `event_kontahent_idkontahent` , `event_kontahent_Firma_idFirma`)
    REFERENCES `mydb`.`event` (`idevent` , `kontahent_idkontahent` , `kontahent_Firma_idFirma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_has_pracownik_pracownik1`
    FOREIGN KEY (`pracownik_idpracownik` , `pracownik_Firma_idFirma` , `pracownik_Dział_idDział`)
    REFERENCES `mydb`.`pracownik` (`idpracownik` , `Firma_idFirma` , `Dział_idDział`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dostawca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dostawca` (
  `idDostawca` INT NOT NULL,
  `Dostawca` VARCHAR(45) NULL,
  `Kontrahent` VARCHAR(45) NULL,
  PRIMARY KEY (`idDostawca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dostawca_has_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dostawca_has_event` (
  `Dostawca_idDostawca` INT NOT NULL,
  `event_idevent` INT NOT NULL,
  `event_kontahent_idkontahent` INT NOT NULL,
  `event_kontahent_Firma_idFirma` INT NOT NULL,
  PRIMARY KEY (`Dostawca_idDostawca`, `event_idevent`, `event_kontahent_idkontahent`, `event_kontahent_Firma_idFirma`),
  INDEX `fk_Dostawca_has_event_event1_idx` (`event_idevent` ASC, `event_kontahent_idkontahent` ASC, `event_kontahent_Firma_idFirma` ASC) VISIBLE,
  INDEX `fk_Dostawca_has_event_Dostawca1_idx` (`Dostawca_idDostawca` ASC) VISIBLE,
  CONSTRAINT `fk_Dostawca_has_event_Dostawca1`
    FOREIGN KEY (`Dostawca_idDostawca`)
    REFERENCES `mydb`.`Dostawca` (`idDostawca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dostawca_has_event_event1`
    FOREIGN KEY (`event_idevent` , `event_kontahent_idkontahent` , `event_kontahent_Firma_idFirma`)
    REFERENCES `mydb`.`event` (`idevent` , `kontahent_idkontahent` , `kontahent_Firma_idFirma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
