-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 16:25:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hotel` (
  `idHotel` INT NOT NULL,
  `Nazwa_hotelu` VARCHAR(45) NULL,
  `Lokalizacja` VARCHAR(45) NULL,
  PRIMARY KEY (`idHotel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Klient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Klient` (
  `idKlient` INT NOT NULL,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `Telefon` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idKlient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rezerwacja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rezerwacja` (
  `idRezerwacja` INT NOT NULL,
  `Data_rezerwacji` VARCHAR(45) NULL,
  `Data_wymeldowania` VARCHAR(45) NULL,
  `Platnosc` VARCHAR(45) NULL,
  `Klient_idKlient` INT NOT NULL,
  PRIMARY KEY (`idRezerwacja`, `Klient_idKlient`),
  INDEX `fk_Rezerwacja_Klient1_idx` (`Klient_idKlient` ASC) VISIBLE,
  CONSTRAINT `fk_Rezerwacja_Klient1`
    FOREIGN KEY (`Klient_idKlient`)
    REFERENCES `mydb`.`Klient` (`idKlient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pokoj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pokoj` (
  `idPokoj` INT NOT NULL,
  `Cena` VARCHAR(45) NULL,
  `Typ_pokoju` VARCHAR(45) NULL,
  `Nr_pokoju` VARCHAR(45) NULL,
  `Hotel_idHotel` INT NOT NULL,
  `Rezerwacja_idRezerwacja` INT NOT NULL,
  PRIMARY KEY (`idPokoj`, `Hotel_idHotel`, `Rezerwacja_idRezerwacja`),
  INDEX `fk_Pokoj_Hotel_idx` (`Hotel_idHotel` ASC) VISIBLE,
  INDEX `fk_Pokoj_Rezerwacja1_idx` (`Rezerwacja_idRezerwacja` ASC) VISIBLE,
  CONSTRAINT `fk_Pokoj_Hotel`
    FOREIGN KEY (`Hotel_idHotel`)
    REFERENCES `mydb`.`Hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokoj_Rezerwacja1`
    FOREIGN KEY (`Rezerwacja_idRezerwacja`)
    REFERENCES `mydb`.`Rezerwacja` (`idRezerwacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uslugi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uslugi` (
  `idUslugi` INT NOT NULL,
  `Typ_uslugi` VARCHAR(45) NULL,
  `Cena` VARCHAR(45) NULL,
  `Rezerwacja_idRezerwacja` INT NOT NULL,
  `Rezerwacja_Klient_idKlient` INT NOT NULL,
  PRIMARY KEY (`idUslugi`, `Rezerwacja_idRezerwacja`, `Rezerwacja_Klient_idKlient`),
  INDEX `fk_Uslugi_Rezerwacja1_idx` (`Rezerwacja_idRezerwacja` ASC, `Rezerwacja_Klient_idKlient` ASC) VISIBLE,
  CONSTRAINT `fk_Uslugi_Rezerwacja1`
    FOREIGN KEY (`Rezerwacja_idRezerwacja` , `Rezerwacja_Klient_idKlient`)
    REFERENCES `mydb`.`Rezerwacja` (`idRezerwacja` , `Klient_idKlient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
