-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 16:55:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Oddzial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Oddzial` (
  `idOddzial` INT NOT NULL,
  `Nazwa_oddzialu` VARCHAR(45) NULL,
  `Adres` VARCHAR(45) NULL,
  PRIMARY KEY (`idOddzial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`samochod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`samochod` (
  `idsamochod` INT NOT NULL,
  `Marka` VARCHAR(45) NULL,
  `Model` VARCHAR(45) NULL,
  `Rocznik` VARCHAR(45) NULL,
  `Typ` VARCHAR(45) NULL,
  `Dostepnosc` VARCHAR(45) NULL,
  `Oddzial_idOddzial` INT NOT NULL,
  PRIMARY KEY (`idsamochod`, `Oddzial_idOddzial`),
  INDEX `fk_samochod_Oddzial_idx` (`Oddzial_idOddzial` ASC) VISIBLE,
  CONSTRAINT `fk_samochod_Oddzial`
    FOREIGN KEY (`Oddzial_idOddzial`)
    REFERENCES `mydb`.`Oddzial` (`idOddzial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Klient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Klient` (
  `idKlient` INT NOT NULL,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `Telefon` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Adres` VARCHAR(45) NULL,
  PRIMARY KEY (`idKlient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wynajem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wynajem` (
  `idWynajem` INT NOT NULL,
  `Data_wynajmu` VARCHAR(45) NULL,
  `Data_zwortu` VARCHAR(45) NULL,
  `Cena` VARCHAR(45) NULL,
  `Klient_idKlient` INT NOT NULL,
  `samochod_idsamochod` INT NOT NULL,
  `samochod_Oddzial_idOddzial` INT NOT NULL,
  PRIMARY KEY (`idWynajem`, `Klient_idKlient`, `samochod_idsamochod`, `samochod_Oddzial_idOddzial`),
  INDEX `fk_Wynajem_Klient1_idx` (`Klient_idKlient` ASC) VISIBLE,
  INDEX `fk_Wynajem_samochod1_idx` (`samochod_idsamochod` ASC, `samochod_Oddzial_idOddzial` ASC) VISIBLE,
  CONSTRAINT `fk_Wynajem_Klient1`
    FOREIGN KEY (`Klient_idKlient`)
    REFERENCES `mydb`.`Klient` (`idKlient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Wynajem_samochod1`
    FOREIGN KEY (`samochod_idsamochod` , `samochod_Oddzial_idOddzial`)
    REFERENCES `mydb`.`samochod` (`idsamochod` , `Oddzial_idOddzial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
